# This is a basic workflow to help you get started with Actions

name: Deploy API to Server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "production" branch
  push:
    branches: [ "production", "backend" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

        # create dotenv
      - name: Create dotenv
        uses: iamsauravsharma/create-dotenv@v3.1.0
        with:
          input-prefix: ENV_
          file-path: ./backend/.env
        env:
          ENV_ENVIRONMENT: \u0022${{ vars.ENVIRONMENT }}\u0022
          # Project info
          ENV_PROJECT_NAME: \u0022${{ vars.PROJECT_NAME }}\u0022
          ENV_PROJECT_VERSION: \u0022${{ vars.PROJECT_VERSION }}\u0022
          # API variables
          ENV_API_PROTOCOL: \u0022${{ vars.API_PROTOCOL }}\u0022
          ENV_API_HOST_IP: \u0022${{ secrets.API_HOST_IP }}\u0022
          ENV_API_BIND_IP: \u0022${{ secrets.API_HOST_IP }}\u0022
          ENV_API_PORT: ${{ secrets.API_PORT }}
          ENV_API_WORKERS: ${{ vars.API_WORKERS }}
          ENV_API_SECRET_KEY: \u0022${{ secrets.API_SECRET_KEY}}\u0022
          ENV_API_ALGORITHM: \u0022${{ secrets.API_ALGORITHM}}\u0022
          # Database variables
          ENV_DB_HOST: \u0022${{ secrets.DB_HOST }}\u0022
          ENV_DB_PORT: \u0022${{ secrets.DB_PORT }}\u0022
          ENV_DB_DSN_ALIAS: \u0022${{ secrets.DB_DSN_ALIAS }}\u0022
          ENV_DB_TNS_FILE_NAME: \u0022${{ secrets.DB_TNS_FILE_NAME }}\u0022
          ENV_DB_USER: \u0022${{ secrets.DB_USER }}\u0022
          ENV_DB_PASSWORD: \u0022${{ secrets.DB_PASSWORD }}\u0022
          ENV_DB_WALLET_DIR_NAME: \u0022${{ secrets.DB_WALLET_DIR_NAME }}\u0022
          ENV_DB_PEM_FILE_NAME: \u0022${{ secrets.DB_PEM_FILE_NAME }}\u0022
          ENV_DB_WALLET_PASSWORD: \u0022${{ secrets.DB_WALLET_PASSWORD }}\u0022
          # other variables
          ENV_LOGS_DIR_NAME: \u0022${{ vars.LOGS_DIR_NAME }}\u0022
          #tmux variables
          ENV_API_SCREEN_NAME: \u0022${{ secrets.API_SCREEN_NAME }}\u0022

        # send dotenv to server
      - name: Copy single file
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          path: ./backend/.env
          remote_path: /home/${{ secrets.SERVER_USER}}/${{ vars.DEPLOY_DIRECTORY}}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_port: ${{ secrets.SERVER_PORT }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_KEY }}
          remote_key_pass: ${{ secrets.SERVER_KEY_PASS }}

        # deploy to server
      - name: Deploy with github
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_KEY_PASS }}
          script: |
            cd ${{ vars.DEPLOY_DIRECTORY }}
            git checkout ${{ github.event.inputs.branch }}
            git fetch --all
            git pull
            bash ./start-api.sh
